### ISSUE TITLE
yahoo finance

### ISSUE THREAD

**Issue by waudinio27** [tblume1992/ThymeBoost#15]
Hey Hello! 

You said in Medium to add some examples with jupyter notebook. 
Could you show a multivariate model that predicts stock prices with yahoo finance data and does out of sample prediction with the model?

Greetings M.

**Comment by tblume1992** [comment]
Hey for sure. Added a quick example here: https://github.com/tblume1992/ThymeBoost/blob/main/Examples/Exogenous%20Example.ipynb

I would install the latest 0.1.9 from pip, added some exogenous stability fixes. Let me know if this all works and I'll continue adding more to the examples!

**Comment by waudinio27** [comment]
I did install the last version and everything is running smooth. I want to ask in addition on how to predict the next lets say 20 steps after the train test part. So the predictions from now on. This is not clear for me .... Otherwise I enjoy playing around with the program - it is fitting the data very fast :-D

**Comment by tblume1992** [comment]
Definitely will do when I get a chance!

Glad you are enjoying the package!
