### ISSUE TITLE
Multiple seasonal periods?

### ISSUE THREAD

**Issue by CoteDave** [tblume1992/ThymeBoost#2]
Hi,

Suppose I have a daily time serie with weekly, monthly and yearly seasonnalities.

Is it possible to mix the 3 seasonalities together ? 

Because if we write seasonal_period=[7, 30, 365] in the boosted_model.optimize, it will choose the best of the 3... however, the best one is the combination of the 3 seasonalities!

Thanks!

**Comment by CoteDave** [comment]
I think i found the way:

seasonal_period=[[7, 30, 365]] seems to do the job!

However, can we extract each seasonalities compound individually ? Because when we do boosted_model.plot_components(output), it only plot the combined seasonalities ?

Thanks!

**Comment by tblume1992** [comment]
Yep, when using optimize or ensemble you must pass all the standard arguments as a list where each element would belong to a single fit. 
The ability to view each individual seasonality is definitely a good idea and I'll add it to the TODO list. It isn't currently built out but you can gain access to each round's seasonality (or trend/exogenous as well). Think this should work:

seasonality_rounds = boosted_model.booster_obj.seasonalities
weekly = seasonality_rounds[::3]
monthly = seasonality_rounds[1::3]
yearly = seasonality_rounds[2::3]

Then just sum up each piece.
