### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by waudinio27** [tblume1992/ThymeBoost#24]
After upgrading to the current version I get - 

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [10], in <cell line: 10>()
      1 boosted_model = tb.ThymeBoost(verbose=0)
      2 output = boosted_model.fit(y_train,
      3                            trend_estimator=['linear','ses'],
      4                            seasonal_estimator='fourier',
   (...)
      8                             exogenous=X_train,
      9                            )
---> 10 predicted_output = boosted_model.predict(output, 5, future_exogenous=X_test)

File ~\anaconda3\lib\site-packages\ThymeBoost\ThymeBoost.py:376, in ThymeBoost.predict(self, fitted_output, forecast_horizon, future_exogenous, damp_factor, trend_cap_target, trend_penalty, uncertainty)
    374     self.scale_type = self._online_learning_ignore_params['scale_type']
    375 if self.ensemble_boosters is None:
--> 376     trend, seas, exo, predictions = predict_rounds(self.booster_obj,
    377                                                    forecast_horizon,
    378                                                    trend_penalty,
    379                                                    future_exogenous,
    380                                                    self.online_learning
    381                                                    )
    382     fitted_output = copy.deepcopy(fitted_output)
    383     predicted_output = self.builder.build_predicted_df(fitted_output,
    384                                                        forecast_horizon,
    385                                                        trend,
   (...)
    390                                                        damp_factor,
    391                                                        uncertainty)

File ~\anaconda3\lib\site-packages\ThymeBoost\predict_functions.py:135, in predict_rounds(booster_obj, forecast_horizon, trend_penalty, future_exo, online_learning)
    127     trend_predictions += predict_trend(booster_obj,
    128                                        boosting_round,
    129                                        forecast_horizon,
    130                                        trend_penalty,
    131                                        online_learning)
    132     seasonal_predictions += predict_seasonality(booster_obj,
    133                                                 boosting_round,
    134                                                 forecast_horizon)
--> 135     exo_predictions += predict_exogenous(booster_obj,
    136                                          future_exo,
    137                                          boosting_round,
    138                                          forecast_horizon)
    139 predictions = (trend_predictions +
    140                seasonal_predictions +
    141                exo_predictions)
    142 return trend_predictions, seasonal_predictions, exo_predictions, predictions

TypeError: ufunc 'add' output (typecode 'O') could not be coerced to provided output parameter (typecode 'd') according to the casting rule ''same_kind''

**Comment by tblume1992** [comment]
What was the previous version it worked in? 0.1.9?

**Comment by waudinio27** [comment]
Yes

**Comment by tblume1992** [comment]
Does it only error when passing exogenous data to be fit? Try without that and if it still errors let me know the types and sizes of X_train, X_test, and y_train.

**Comment by waudinio27** [comment]
It stays the same without exogenous. 
It also occurs with another model. Here is the model and the error. 

from ThymeBoost import ThymeBoost as tb


current_df = df.iloc[0:-1:].reset_index()
future_df = df.iloc[:10].reset_index()


Indikatoren = ['JP225_USD', 'EU50_EUR', 'FR40_EUR', 'WTICO_USD']

y_train = current_df['DE30_EUR']
X_train = current_df[Indikatoren]

y_test = future_df['DE30_EUR']
X_test = future_df[Indikatoren]




boosted_model = tb.ThymeBoost(approximate_splits=True,
                            n_split_proposals=25,
                            verbose=1,
                            cost_penalty=.001,
                            )
output = boosted_model.fit(y_train,
                           trend_estimator=['linear','ses'],
                           seasonal_estimator='fourier',
                           
                           global_cost='mse',
                           exogenous_estimator='ols',
                           fit_type=['local', 'global'],
                           
                            exogenous=X_train,
                           )
predicted_output = boosted_model.predict(output, 10, future_exogenous=X_test)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [13], in <cell line: 6>()
      1 boosted_model = tb.ThymeBoost(approximate_splits=True,
      2                             n_split_proposals=25,
      3                             verbose=1,
      4                             cost_penalty=.001,
      5                             )
----> 6 output = boosted_model.fit(y_train,
      7                            trend_estimator=['linear','ses'],
      8                            seasonal_estimator='fourier',
      9                            
     10                            global_cost='mse',
     11                            exogenous_estimator='ols',
     12                            fit_type=['local', 'global'],
     13                            
     14                             exogenous=X_train,
     15                            )
     16 predicted_output = boosted_model.predict(output, 10, future_exogenous=X_test)

File ~\anaconda3\lib\site-packages\ThymeBoost\ThymeBoost.py:319, in ThymeBoost.fit(self, time_series, seasonal_period, trend_estimator, seasonal_estimator, exogenous_estimator, l2, poly, arima_order, arima_trend, connectivity_constraint, fourier_order, fit_type, window_size, trend_weights, seasonality_weights, trend_lr, seasonality_lr, exogenous_lr, min_sample_pct, split_cost, global_cost, exogenous, damp_factor, ewm_alpha, alpha, beta, ransac_trials, ransac_min_samples, tree_depth, additive, init_trend)
    305 time_series = self.scale_input(time_series)
    306 self.booster_obj = booster(time_series=time_series,
    307                            given_splits=self.given_splits,
    308                            verbose=self.verbose,
   (...)
    317                            split_strategy=self.split_strategy,
    318                            **_params)
--> 319 booster_results = self.booster_obj.boost()
    320 fitted_trend = booster_results[0]
    321 fitted_seasonality = booster_results[1]

File ~\anaconda3\lib\site-packages\ThymeBoost\fitter\booster.py:125, in booster.boost(self)
    123 if self.i == self.n_rounds:
    124     break
--> 125 round_results = self.additive_boost_round(self.i)
    126 current_prediction, total_trend, total_seasonal, total_exo = round_results
    127 resids = self.time_series - current_prediction

File ~\anaconda3\lib\site-packages\ThymeBoost\fitter\decompose.py:120, in Decompose.additive_boost_round(self, round_number)
    118 self.boosted_data -= seasonality
    119 if self.boosting_params['exogenous'] is not None:
--> 120     self.get_exogenous_component(self.boosted_data)
    121 #self.errors.append(np.mean(np.abs(self.boosted_data)))
    122 total_trend = np.sum(self.trends, axis=0)

File ~\anaconda3\lib\site-packages\ThymeBoost\fitter\decompose.py:102, in Decompose.get_exogenous_component(self, residual)
     99 def get_exogenous_component(self, residual):
    100     self.exo_class = FitExogenous(self.boosting_params['exogenous_estimator'],
    101                                   **self.boosting_params)
--> 102     exo_fit = self.exo_class.fit_exogenous_component(self.boosted_data,
    103                                                      self.boosting_params['exogenous'],
    104                                                      )
    105     self.fitted_exogenous.append(exo_fit)
    106     self.boosted_data = self.boosted_data - exo_fit

File ~\anaconda3\lib\site-packages\ThymeBoost\fit_components\fit_exogenous.py:34, in FitExogenous.fit_exogenous_component(self, time_residual, exogenous)
     32 if isinstance(exogenous, pd.DataFrame):
     33     exogenous = exogenous.to_numpy()
---> 34 exo_fitted = self.model_obj.fit(time_residual, exogenous, **self.kwargs)
     35 return self.exogenous_lr*np.array(exo_fitted)

File ~\anaconda3\lib\site-packages\ThymeBoost\exogenous_models\ols_exogenous.py:16, in OLS.fit(self, y, X, **kwargs)
     15 def fit(self, y, X, **kwargs):
---> 16     exo_model = sm.OLS(y, X)
     17     self.model_obj = exo_model.fit()
     18     self.fitted = self.model_obj.predict(X)

File ~\anaconda3\lib\site-packages\statsmodels\regression\linear_model.py:890, in OLS.__init__(self, endog, exog, missing, hasconst, **kwargs)
    887     msg = ("Weights are not supported in OLS and will be ignored"
    888            "An exception will be raised in the next version.")
    889     warnings.warn(msg, ValueWarning)
--> 890 super(OLS, self).__init__(endog, exog, missing=missing,
    891                           hasconst=hasconst, **kwargs)
    892 if "weights" in self._init_keys:
    893     self._init_keys.remove("weights")

File ~\anaconda3\lib\site-packages\statsmodels\regression\linear_model.py:717, in WLS.__init__(self, endog, exog, weights, missing, hasconst, **kwargs)
    715 else:
    716     weights = weights.squeeze()
--> 717 super(WLS, self).__init__(endog, exog, missing=missing,
    718                           weights=weights, hasconst=hasconst, **kwargs)
    719 nobs = self.exog.shape[0]
    720 weights = self.weights

File ~\anaconda3\lib\site-packages\statsmodels\regression\linear_model.py:191, in RegressionModel.__init__(self, endog, exog, **kwargs)
    190 def __init__(self, endog, exog, **kwargs):
--> 191     super(RegressionModel, self).__init__(endog, exog, **kwargs)
    192     self._data_attr.extend(['pinv_wexog', 'wendog', 'wexog', 'weights'])

File ~\anaconda3\lib\site-packages\statsmodels\base\model.py:267, in LikelihoodModel.__init__(self, endog, exog, **kwargs)
    266 def __init__(self, endog, exog=None, **kwargs):
--> 267     super().__init__(endog, exog, **kwargs)
    268     self.initialize()

File ~\anaconda3\lib\site-packages\statsmodels\base\model.py:92, in Model.__init__(self, endog, exog, **kwargs)
     90 missing = kwargs.pop('missing', 'none')
     91 hasconst = kwargs.pop('hasconst', None)
---> 92 self.data = self._handle_data(endog, exog, missing, hasconst,
     93                               **kwargs)
     94 self.k_constant = self.data.k_constant
     95 self.exog = self.data.exog

File ~\anaconda3\lib\site-packages\statsmodels\base\model.py:132, in Model._handle_data(self, endog, exog, missing, hasconst, **kwargs)
    131 def _handle_data(self, endog, exog, missing, hasconst, **kwargs):
--> 132     data = handle_data(endog, exog, missing, hasconst, **kwargs)
    133     # kwargs arrays could have changed, easier to just attach here
    134     for key in kwargs:

File ~\anaconda3\lib\site-packages\statsmodels\base\data.py:673, in handle_data(endog, exog, missing, hasconst, **kwargs)
    670     exog = np.asarray(exog)
    672 klass = handle_data_class_factory(endog, exog)
--> 673 return klass(endog, exog=exog, missing=missing, hasconst=hasconst,
    674              **kwargs)

File ~\anaconda3\lib\site-packages\statsmodels\base\data.py:86, in ModelData.__init__(self, endog, exog, missing, hasconst, **kwargs)
     84 self.const_idx = None
     85 self.k_constant = 0
---> 86 self._handle_constant(hasconst)
     87 self._check_integrity()
     88 self._cache = {}

File ~\anaconda3\lib\site-packages\statsmodels\base\data.py:131, in ModelData._handle_constant(self, hasconst)
    129 check_implicit = False
    130 exog_max = np.max(self.exog, axis=0)
--> 131 if not np.isfinite(exog_max).all():
    132     raise MissingDataError('exog contains inf or nans')
    133 exog_min = np.min(self.exog, axis=0)

TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

I hope it helps ....

**Comment by tblume1992** [comment]
Yeah numpy is not happy. I was able to recreate the errors on my end and I think your data is of type object rather than float or int. Try converting your dataframe types to float right before you pass to ThymeBoost:
```
X_train = X_train.astype(float)
X_test = X_test.astype(float)
```

Let me know if the error persists! I'll add some type checks for exogenous in the next push.

**Comment by waudinio27** [comment]
Works like a charme again. The astype(float) did the trick :-D 
Do you mainly advise to use the global fit alone with the AutoARIMA like in the example as it otherwise takes a lot of time? 

Thanks an have a nice weekend :-D

**Comment by tblume1992** [comment]
Great!

Yes, any model that is a smoother or fits with windows or has some sense of 'local' fitting built into it probably shouldn't be fit with 'local'.

 So models like:

1. loess
2. ewm
3. ses,des,damped_des (the smoothers)
4. ARIMA
5. moving_average

It could be useful if you _know_ there is a changepoint to fit locally for something like an ARIMA since it allows the coefficients to be different, but typically it will just overfit or do nothing for these methods. 

If you do want to allow for changepoints with ARIMA you can control how many changepoints the model tries out by using:
`ThymeBoost(split_strategy='gradient',
n_split_proposals=n,
approximate_splits=True)`

Where n is the number of splits to try, so the lower means the faster it fits. But this is still a slow process!

Have a good weekend as well!
