### ISSUE TITLE
Exogenous Features

### ISSUE THREAD

**Issue by CoteDave** [tblume1992/ThymeBoost#4]
Hi,

I don't know if it's a bug, but adding exogenous features seems not working:

![image](https://user-images.githubusercontent.com/49559881/142453221-1496ca76-bd87-46bd-b75e-4644f58c4de8.png)

![image](https://user-images.githubusercontent.com/49559881/142453281-1d980cd1-a48b-46ef-8d73-385bd6c39510.png)

**Comment by CoteDave** [comment]
Specification:

It does work when single seasonal_period or single trend_estimator, when asking for combined, not working:

Single seasonal_periods + single trend estimator WORK:
![image](https://user-images.githubusercontent.com/49559881/142456439-1d567e5f-d962-4073-a659-f060217b5a2e.png)

Multiple seasonal_periods + Single trend estimator NOT WORKING:
![image](https://user-images.githubusercontent.com/49559881/142456665-4d85a762-ed3c-4f93-91ca-bf44da10e067.png)

![image](https://user-images.githubusercontent.com/49559881/142456588-c69ab33c-ff4f-41b2-8017-4c3fdfbcad69.png)

Single seasonal_periods + Multiple trend estimator NOT WORKING:
![image](https://user-images.githubusercontent.com/49559881/142456888-f665ca0c-955a-400b-93f5-eb32c38de9b0.png)

![image](https://user-images.githubusercontent.com/49559881/142456795-7eb05188-76b9-46e2-9054-e14541903609.png)

**Comment by tblume1992** [comment]
For the optimize issue: Everything that would normally be passed to fit that is being passed to optimize or ensemble needs to be wrapped in a list.  So exogenous_estimator and exogenous needs list brackets and it should work.

Your second issue is using the normal fit method so it is fine to pass non-lists.  And if you do pass lists then it will use those as 'Generator' variables, see the README and ctrl f to learn some more about those. BUT you are passing list of lists which won't work for fit.  

Just be careful when you are using standard fit vs optimize/ensemble methods as the variable requirements change.

Don't see anything that is working incorrectly here.

**Comment by tblume1992** [comment]
I will say (after looking more into this more) there is a lot of instability with using exogenous and optimize primarily due to the index of the exogenous being referenced to create test sets. I'll try to address this in the next push but for now just be very careful when passing exogenous stuff.  I would make sure everything is a dataframe and when predicting the future_exogenous dataframe index lines up with the one passed to fit/optimize/ensemble.

**Comment by CoteDave** [comment]
Thanks! Great library by the way! Time Serie Decomposition is the key to build a great forcasting model, ThymeBoost is very ingenious and powerfull!
