### ISSUE TITLE
Arima trend returns error

### ISSUE THREAD

**Issue by curlylocks1987** [tblume1992/ThymeBoost#6]
![image](https://user-images.githubusercontent.com/51542174/144567454-785f12c4-7f76-4cf8-9fab-e3a790abd89a.png)

**Comment by tblume1992** [comment]
This looks like a statsmodels version issue, I would update it:
`pip install statsmodels --upgrade`
Let me know if that solves it!

**Comment by curlylocks1987** [comment]
Yes, it resumed working, thank you!
