### ISSUE TITLE
forecasting with future_exogenous values

### ISSUE THREAD

**Issue by phillip1029** [tblume1992/ThymeBoost#7]
I have a model specification like below: 

future_exog = x_df[-1:]
boosted_model = tb.ThymeBoost(approximate_splits=True,
                              n_split_proposals=10,
                              verbose=1,
                              cost_penalty=.001)
output = boosted_model.fit(df['y'][:-1].values,
                           trend_estimator='linear',
                           seasonal_estimator='fourier',
                           seasonal_period=4,
                           split_cost='mae',
                           global_cost='maicc',
                           exogenous=x_df[:-1],
                           fit_type='global')
predicted_output = boosted_model.predict(output, forecast_horizon=1, future_exogenous=future_exog)  

The model fit works fine with the exogenous variables but the predict function does not pick up the future_exogeneous variable values. The output dataframe looks like: 

        y   exogenous        yhat  yhat_upper  yhat_lower  seasonality  \
13  298.0   11.974441  276.813790  394.821765  158.805814    14.543604   
14  283.0   57.310657  302.120516  420.128492  184.112541    -5.855722   
15  196.0   62.654007  310.999059  429.007035  192.991083    -2.690368

but the predicted_output looks like:

predictions  predicted_trend  predicted_seasonality  predicted_exogenous  \
   NaN                252.144933              -5.855722                  NaN   

    predicted_upper  predicted_lower  
           NaN              NaN  

But the future_exogenous is not NaN. 

Did I miss anything?

**Comment by tblume1992** [comment]
Future exog can be finicky still. I would try to pass your exog inputs as 2d so: 

```
exogenous=x_df[:-1].reshape((-1,1)) 
future_exog=x_df[-1:].reshape((-1,1)) 
```

If that doesn't work I am considering standardizing exogenous inputs as dataframes with datetime index as it is the most 'stable'.  

So you could try keeping your input time series as a series with a datetime index then pass exogenous as a **dataframe** with that same datetime index. Then pass future exogenous as a **dataframe** with the **future** datetime index.

**Comment by phillip1029** [comment]
@tblume1992, Thank you very much. It works now.
